--EXPLORATORY DATA ANALYSIS
--PREVIEW TABLES

SELECT TOP 5 * FROM MEDICARE_CHARGE_INPATIENT_DRG100_DRG_SUMMARY;
SELECT TOP 5 * FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100 ;

SELECT TOP 5 * FROM MEDICARE_CHARGE_OUTPATIENT_APC30_SUMMARY;
SELECT TOP 5 * FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30;

SELECT *  FROM REVIEW_PATIENT_HISTORY
EXCEPT
SELECT  * FROM PATIENT_HISTORY

--APPENDING THE TABLE TO INCLUDE ALL THE ROWS

SELECT * INTO ALL_PATIENT_HISTORY FROM
(SELECT *  FROM REVIEW_PATIENT_HISTORY
UNION
SELECT  * FROM PATIENT_HISTORY) T ;


SELECT  * FROM RREVIEW_TRANSACTION ;

SELECT * FROM [TRANSACTION];


--TOTAL RECORDS


SELECT COUNT (*) AS TOTAL_ROWS,'MEDICARE_CHARGE_INPATIENT_DRG100_DRG_SUMMARY' AS TABLE_NAME FROM MEDICARE_CHARGE_INPATIENT_DRG100_DRG_SUMMARY
UNION
SELECT COUNT (*) AS TOTAL_ROWS,'MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100' AS TABLE_NAME  FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100
UNION
SELECT COUNT (*) AS TOTAL_ROWS,'MEDICARE_CHARGE_OUTPATIENT_APC30_SUMMARY' AS TABLE_NAME FROM MEDICARE_CHARGE_OUTPATIENT_APC30_SUMMARY
UNION
SELECT COUNT (*) AS TOTAL_ROWS, 'MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30' AS TABLE_NAME FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30
UNION
SELECT COUNT (*) AS TOTAL_ROWS, 'REVIEW_PATIENT_HISTORY' AS TABLE_NAME FROM REVIEW_PATIENT_HISTORY
UNION
SELECT COUNT (*) AS TOTAL_ROWS,'PATIENT_HISTORY' AS TABLE_NAME FROM PATIENT_HISTORY
UNION
SELECT COUNT (*) AS TOTAL_ROWS,'ALL_PATIENT_HISTORY' AS TABLE_NAME FROM ALL_PATIENT_HISTORY
UNION
SELECT COUNT (*) AS TOTAL_ROWS,'RREVIEW_TRANSACTION' AS TABLE_NAME FROM RREVIEW_TRANSACTION
UNION
SELECT COUNT (*) AS TOTAL_ROWS,'TRANSACTION' AS TABLE_NAME FROM [TRANSACTION]
ORDER BY TOTAL_ROWS;


--CHECKING FOR DUPLICATES     NO DUPS
SELECT *
FROM
(
SELECT *
, DUPRANK = ROW_NUMBER() OVER (
              PARTITION BY DRG_DEFINITION,PROVIDER_ID,PROVIDER_NAME,	PROVIDER_STREET_ADDRESS,PROVIDER_CITY,PROVIDER_STATE,	PROVIDER_ZIP_CODE,HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION,	TOTAL_DISCHARGES,	AVERAGE_COVERED_CHARGES, AVERAGE_TOTAL_PAYMENTS,AVERAGE_MEDICARE_PAYMENTS
              ORDER BY (SELECT NULL) )
FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100
) AS T
WHERE DUPRANK > 1;

SELECT *
FROM
(
SELECT *
, DUPRANK = ROW_NUMBER() OVER (
              PARTITION BY APC,	PROVIDER_ID,	PROVIDER_NAME,	PROVIDER_STREET_ADDRESS,	PROVIDER_CITY,	PROVIDER_STATE,	PROVIDER_ZIP_CODE,	HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION,	OUTPATIENT_SERVICES,	AVERAGE_ESTIMATED_SUBMITTED_CHARGES,	AVERAGE_TOTAL_PAYMENTS
              ORDER BY (SELECT NULL) )
FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30
) AS T
WHERE DUPRANK > 1;


SELECT *
FROM
(
SELECT *
, DUPRANK = ROW_NUMBER() OVER (
              PARTITION BY ID,AGE,GENDER,INCOME
              ORDER BY (SELECT NULL) )
FROM PATIENT_HISTORY
) AS T
WHERE DUPRANK > 1;


SELECT *
FROM
(
SELECT *
, DUPRANK = ROW_NUMBER() OVER (
              PARTITION BY ID,GLOBAL_PROC_ID,[COUNT]
              ORDER BY (SELECT NULL) )
FROM [TRANSACTION]
) AS T
WHERE DUPRANK > 1;

--CHECKING FOR NULL OR MISSING VALUES

--5049 ROWS HAVE NULL
SELECT * FROM PATIENT_HISTORY AS P
WHERE P.ID IS NULL 
OR P.GENDER IS NULL
OR P.AGE IS NULL
OR P.INCOME IS NULL;

--52 ROWS HAVE NULL
SELECT * FROM REVIEW_PATIENT_HISTORY AS P
WHERE P.ID IS NULL 
OR P.GENDER IS NULL
OR P.AGE IS NULL
OR P.INCOME IS NULL;


--DISTINCT VALUES
SELECT 
COUNT(DISTINCT(APC)) APC_COUNT,
COUNT(DISTINCT(PROVIDER_ID)) PROVIDER_COUNT,
COUNT(DISTINCT(PROVIDER_NAME)) PROVIDER_NAME_COUNT,
COUNT(DISTINCT(PROVIDER_STREET_ADDRESS)) STREET_COUNT,	
COUNT(DISTINCT(PROVIDER_CITY)) CITY_COUNT,	
COUNT(DISTINCT(PROVIDER_STATE)) STATE_COUNT,	
COUNT(DISTINCT(PROVIDER_ZIP_CODE)) ZIP_CODE_COUNY ,	
COUNT(DISTINCT(HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION)) HRR_COUNT
FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30 

SELECT 
COUNT(DISTINCT(DRG_DEFINITION)) DRG_COUNT,
COUNT(DISTINCT(PROVIDER_ID)) PROVIDER_COUNT,
COUNT(DISTINCT(PROVIDER_NAME)) PROVIDER_NAME_COUNT,
COUNT(DISTINCT(PROVIDER_STREET_ADDRESS)) STREET_COUNT,	
COUNT(DISTINCT(PROVIDER_CITY)) CITY_COUNT,	
COUNT(DISTINCT(PROVIDER_STATE)) STATE_COUNT,	
COUNT(DISTINCT(PROVIDER_ZIP_CODE)) ZIP_CODE_COUNY ,	
COUNT(DISTINCT(HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION)) HRR_COUNT
FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100 

SELECT COUNT(DISTINCT(ID)) NO_ID,
COUNT(DISTINCT(AGE)) AGE_CAT,
COUNT(DISTINCT(GENDER)) GENDER_CAT,
COUNT(DISTINCT(INCOME)) INCOME_CAT
FROM TRANSACTION_SUMMARY


--JOINING TRANSACTION WITH PATIENT HISTORY
-- CREATING TRANSACTION SUMMARY OF PATIENT

SELECT T.ID,SUM([COUNT]) N_COUNT,AGE,GENDER,INCOME,global_proc_id
INTO TRANSACTION_SUMMARY
FROM [TRANSACTION] T
LEFT JOIN ALL_PATIENT_HISTORY P ON
P.ID=T.ID
GROUP BY T.ID,AGE,GENDER,INCOME,global_proc_id
ORDER BY N_COUNT DESC

-- global proc id patient distribution
SELECT global_proc_id, COUNT(DISTINCT(id)) as Patient_count FROM Transaction_Summary
Group by global_proc_id
order by Patient_count desc

--PROVIDER THAT PROVIDE ONLY INPATIENT SERVICE
SELECT PROVIDER_ID FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100
EXCEPT
SELECT PROVIDER_ID FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30

--INPATIENT DATA
--PROVIDER WHERE AVG AMOUNT RECIEVED IS GREATEAR THAN OVERALL AVERAGE FOR THAT DRG

SELECT DISTINCT(PROVIDER_ID )
FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100 AS O
LEFT JOIN Medicare_Charge_Inpatient_DRG100_DRG_Summary AS S 
ON O.DRG_DEFINITION =S.DRG_DEFINITION
WHERE O.AVERAGE_TOTAL_PAYMENTS > S.AVERAGE_TOTAL_PAYMENTS;


--INPATIENT DATA   
--HOSPITAL REGIONS and DRG comnination,
--WHERE total payment IS 3 TIMES than AVERAGE IN THAT REGION

SELECT DISTINCT(O.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION),o.DRG_Definition
FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100 AS O
LEFT JOIN 
			(SELECT
			D.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION,D.DRG_Definition,
			AVG(D.Average_Total_Payments) AS AVERAGE_TOTAL_PAYMENTS
			FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100 AS D
			GROUP BY D.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION,D.DRG_Definition) AS S 

ON O.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION =S.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION and
s.DRG_Definition=o.DRG_Definition
WHERE O.AVERAGE_TOTAL_PAYMENTS > 3* S.AVERAGE_TOTAL_PAYMENTS

;


--OUPATIENT DATA   
--PROVIDER WHERE AVG AMOUNT RECIEVED IS GREATEAR THAN OVERALL AVERAGE FOR THAT APC

SELECT DISTINCT(PROVIDER_ID )
FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30 AS O
LEFT JOIN Medicare_Charge_Outpatient_APC30_Summary AS S 
ON O.APC =S.APC
WHERE O.AVERAGE_TOTAL_PAYMENTS > S.AVERAGE_TOTAL_PAYMENTS;




--OUPATIENT DATA   
--HOSPITAL REGIONS and APC combination WHERE AVG AMOUNT RECIEVED IS greater AVERAGE IN THAT REGION

SELECT DISTINCT(O.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION),O.APC
FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30 AS O
LEFT JOIN 
			(SELECT
			D.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION,D.APC,
			AVG(D.AVERAGE_TOTAL_PAYMENTS) AS AVERAGE_TOTAL_PAYMENTS
			FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30 AS D
			GROUP BY D.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION,D.APC) AS S 

ON O.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION =S.HOSPITAL_REFERRAL_REGION_HRR_DESCRIPTION and
o.APC=S.APC
WHERE O.AVERAGE_TOTAL_PAYMENTS > S.AVERAGE_TOTAL_PAYMENTS;


--TOP 10 PATIENTS WITH HIGHEST NUMBER OF TRANSCATION
SELECT TOP 10 T.ID,SUM([COUNT]) N_COUNT,AGE,GENDER,INCOME
FROM [TRANSACTION] T
LEFT JOIN ALL_PATIENT_HISTORY P ON
P.ID=T.ID
GROUP BY T.ID,AGE,GENDER,INCOME
ORDER BY N_COUNT DESC

--PATIENTS INCOME DISTRIBUTION
SELECT INCOME, (COUNT(ID)*100.0)/505000 PCT_PATIENTS
FROM ALL_PATIENT_HISTORY
GROUP BY INCOME
ORDER BY PCT_PATIENTS DESC

--PATIENTS GENDER DISTRIBUTION
SELECT GENDER, (COUNT(ID)*100.0)/505000 PCT_PATIENTS
FROM ALL_PATIENT_HISTORY
GROUP BY GENDER
ORDER BY PCT_PATIENTS DESC

--PATIENTS AGE DISTRIBUTION
SELECT AGE, (COUNT(ID)*100.0)/505000 PCT_PATIENTS
FROM ALL_PATIENT_HISTORY
GROUP BY AGE
ORDER BY PCT_PATIENTS DESC

--MOST USED DRG PROCEDURE IN INPATIENT
SELECT DRG_Definition, SUM(Total_Discharges)*100.0/(SELECT SUM(Total_Discharges) FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100) DISCHARGES_PCT 
FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100 GROUP BY DRG_Definition 
ORDER BY DISCHARGES_PCT DESC

--MOST USED APC SERVICE
SELECT APC, SUM(Outpatient_Services)*100.0/(SELECT SUM(Outpatient_Services) FROM Medicare_Provider_Charge_Outpatient_APC30) APC_PCT 
FROM Medicare_Provider_Charge_Outpatient_APC30 GROUP BY APC 
ORDER BY APC_PCT DESC

--KPIS
--AVERAGE TOTAL PAYMENTS PER OUTPATIENT SERVICE
SELECT SUM(AVERAGE_TOTAL_PAYMENTS)/SUM(OUTPATIENT_SERVICES) AVERAGE_TOTAL_PAYMENTS_PER_OUTPATIENT_SERVICE FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30

--AVERAGE ESTIMATED SUBMITTED CHARGES PER OUTPATIENT SERVICE
SELECT SUM(AVERAGE_ESTIMATED_SUBMITTED_CHARGES)/SUM(OUTPATIENT_SERVICES) AVERAGE_ESTIMATED_SUBMITTED_PER_OUTPATIENT_SERVICE FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30

--OUTPATIENT CHARGE-TO-PAYMENT RATIO
SELECT SUM(AVERAGE_ESTIMATED_SUBMITTED_CHARGES)/SUM(AVERAGE_TOTAL_PAYMENTS) CHARGE_TO_PAYMENT FROM MEDICARE_PROVIDER_CHARGE_OUTPATIENT_APC30

--AVERAGE TOTAL PAYMENTS PER INPATIENT DISCHARGE
SELECT SUM(AVERAGE_TOTAL_PAYMENTS)/SUM(TOTAL_DISCHARGES) AVERAGE_TOTAL_PAYMENTS_PER_INPATIENT_SERVICE FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100

--MEDICARE DEPENDENCE PCT
SELECT SUM(AVERAGE_MEDICARE_PAYMENTS)/SUM(AVERAGE_TOTAL_PAYMENTS)*100 MEDICARE_RELIANCE_PCT FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100

--INPATIENT REIMBURSEMENT PCT
SELECT SUM(AVERAGE_COVERED_CHARGES)/SUM(AVERAGE_TOTAL_PAYMENTS) INPATIENT_REIMBURSEMENT_PCT FROM MEDICARE_PROVIDER_CHARGE_INPATIENT_DRG100

